/-
Copyright (c) 2026 Re'em Melamed-Katz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Re'em Melamed-Katz
-/
import Mathlib.Algebra.Group.Subsemigroup.Basic
import Mathlib.Data.List.Basic

/-!
# Non-empty List Product in Semigroups

Product of a non-empty list of elements in a bare semigroup `S` (without identity `1`).

## References

* [T. Colcombet, *The Factorization Forest Theorem*][colcombet2008]
-/

variable {S : Type*} [Semigroup S]

-- TODO: Upstream to Mathlib.Data.List.SemigroupProd
/-- Product of a non-empty list of elements in a semigroup `S`. -/
def listProdNE : (u : List S) → u ≠ [] → S
  | [], hu => False.elim (hu rfl)
  | a :: rest, _ => rest.foldl (· * ·) a

-- TODO: Upstream to Mathlib.Data.List.SemigroupProd
/-- `List.foldl` multiplication by `x` on the left equals `x * listProdNE v hv`. -/
lemma foldl_mul_eq_mul_listProdNE (x : S) (v : List S) (hv : v ≠ []) :
    v.foldl (· * ·) x = x * listProdNE v hv := by
  revert x
  induction v with
  | nil => contradiction
  | cons b rest ih =>
    intro x
    cases rest with
    | nil => rfl
    | cons c rest' =>
      have h_rest_ne : c :: rest' ≠ [] := by simp
      change List.foldl (· * ·) (x * b) (c :: rest') = x * List.foldl (· * ·) b (c :: rest')
      rw [ih h_rest_ne (x * b), ih h_rest_ne b, mul_assoc]

-- TODO: Upstream to Mathlib.Data.List.SemigroupProd
/-- Product of concatenated non-empty lists is the product of their individual products. -/
lemma listProdNE_concat (u v : List S) (hu : u ≠ []) (hv : v ≠ []) :
    listProdNE (u ++ v) (by simp [hu, hv]) = listProdNE u hu * listProdNE v hv := by
  cases u with
  | nil => contradiction
  | cons a rest =>
    dsimp [listProdNE]
    rw [List.foldl_append]
    exact foldl_mul_eq_mul_listProdNE (rest.foldl (· * ·) a) v hv

-- TODO: Upstream to Mathlib.Data.List.SemigroupProd
/-- Every element in `Subsemigroup.closure X` is generated by
a non-empty list of elements in `X`. -/
lemma mem_closure_iff_exists_list (X : Set S) (s : S) :
    s ∈ Subsemigroup.closure X ↔
    ∃ (u : List S) (hu : u ≠ []), (∀ x ∈ u, x ∈ X) ∧ listProdNE u hu = s := by
  constructor
  · intro hs
    induction hs using Subsemigroup.closure_induction with
    | mem x hx =>
      refine ⟨[x], by simp, by simp [hx], rfl⟩
    | mul x y hx hy ihx ihy =>
      rcases ihx with ⟨ux, hux, hX_x, rfl⟩
      rcases ihy with ⟨uy, huy, hX_y, rfl⟩
      have h_mem : ∀ a ∈ ux ++ uy, a ∈ X := by
        rintro a ha
        rcases List.mem_append.mp ha with h | h
        · exact hX_x a h
        · exact hX_y a h
      exact ⟨ux ++ uy, by simp [hux, huy], h_mem, listProdNE_concat ux uy hux huy⟩
  · rintro ⟨u, hu, hX, rfl⟩
    induction u with
    | nil => contradiction
    | cons a rest ih =>
      cases rest with
      | nil => exact Subsemigroup.subset_closure (hX a (by simp))
      | cons b rest' =>
        have h_rest_ne : b :: rest' ≠ [] := by simp
        have ih' := ih h_rest_ne (fun x hx ↦ hX x (List.mem_cons_of_mem a hx))
        have ha : a ∈ Subsemigroup.closure X := Subsemigroup.subset_closure (hX a (by simp))
        have h_eq : listProdNE (a :: b :: rest') hu = a * listProdNE (b :: rest') h_rest_ne := by
          dsimp [listProdNE]
          exact foldl_mul_eq_mul_listProdNE a (b :: rest') h_rest_ne
        rw [h_eq]
        exact Subsemigroup.mul_mem _ ha ih'

-- TODO: Upstream to Mathlib.Data.List.SemigroupProd
/-- Well-definedness of `listProdNE` with respect to list equality. -/
lemma listProdNE_eq (u v : List S) (hu : u ≠ []) (hv : v ≠ []) (h : u = v) :
    listProdNE u hu = listProdNE v hv := by
  subst h
  rfl

