/-
Copyright (c) 2026 Re'em Melamed-Katz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Re'em Melamed-Katz
-/
import Mathlib.Algebra.Group.Pointwise.Set.Basic
import Mathlib.Algebra.Group.Hom.Basic
import Mathlib.Algebra.Group.Subsemigroup.Basic
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Set.Finite.Range
import Mathlib.Data.Fintype.Basic
import Mathlib.Algebra.Group.Pointwise.Set.Finite
import Mathlib.Order.CompleteLattice.Finset
import Project.SimonSplit.Combine
import Project.SimonSplit.Split

/-!
# Brown's Lemma and Algebraic Applications of Simon's Split Theorem

This file formalizes the proof of Brown's Lemma without using factorization trees.

## References
* [T. Colcombet, *The Factorization Forest Theorem*][colcombet2008]
-/

namespace BrownLemma

open Set SimonSplit
open scoped Pointwise

variable {S T : Type*} [Semigroup S] [Semigroup T]

/-- The Simon complexity `nS S` of any non-empty finite semigroup `S` is strictly positive. -/
lemma nS_pos {S : Type*} [Semigroup S] [Fintype S] [Nonempty S] : 0 < nS S := by
  dsimp [nS]
  have h_ne : (Finset.univ.image (fun (x : S) ↦ nSElement x)).Nonempty := by
    obtain ⟨x⟩ : Nonempty S := inferInstance
    exact ⟨_, Finset.mem_image_of_mem _ (Finset.mem_univ x)⟩
  rw [dif_pos h_ne]
  obtain ⟨x⟩ : Nonempty S := inferInstance
  have h_pos : 0 < nSElement x := nSElement_pos x
  have h_mem : nSElement x ∈ Finset.univ.image (fun (x : S) ↦ nSElement x) :=
    Finset.mem_image_of_mem _ (Finset.mem_univ x)
  exact h_pos.trans_le (Finset.le_max' _ _ h_mem)

/-- `Fin (nS S)` is non-empty for any non-empty finite semigroup `S`. -/
instance instNonemptyFin_nS {S : Type*} [Semigroup S] [Fintype S] [Nonempty S] :
    Nonempty (Fin (nS S)) :=
  Fin.pos_iff_nonempty.mp nS_pos

/-- The inductive sequence of subsets Xₙ ⊆ S.
X₀ = X
Xₙ₊₁ = Xₙ ∪ (Xₙ * Xₙ) ∪ ⋃_{e ∈ T, e² = e} ⟨Xₙ ∩ ϕ⁻¹(e)⟩_S -/
def X_seq (ϕ : S →ₙ* T) (X : Set S) : ℕ → Set S
  | 0 => X
  | n + 1 =>
    let Xn := X_seq ϕ X n
    Xn ∪ (Xn * Xn) ∪ ⋃ (e : T) (_ : e * e = e), (Subsemigroup.closure (Xn ∩ ϕ ⁻¹' {e}) : Set S)

/-- Xₙ ⊆ Xₙ₊₁ for all n. -/
lemma X_seq_succ_self (ϕ : S →ₙ* T) (X : Set S) (n : ℕ) :
    X_seq ϕ X n ⊆ X_seq ϕ X (n + 1) := by
  dsimp [X_seq]
  exact subset_union_left.trans subset_union_left

/-- Xₘ ⊆ Xₙ whenever m ≤ n. -/
lemma X_seq_mono (ϕ : S →ₙ* T) (X : Set S) {m n : ℕ} (h : m ≤ n) :
    X_seq ϕ X m ⊆ X_seq ϕ X n := by
  induction h with
  | refl => exact subset_rfl
  | step hk ih => exact ih.trans (X_seq_succ_self ϕ X _)

/-- Xₙ ⊆ ⟨X⟩_S for all n. -/
lemma X_seq_subset_closure (ϕ : S →ₙ* T) (X : Set S) (n : ℕ) :
    X_seq ϕ X n ⊆ Subsemigroup.closure X := by
  induction n with
  | zero => exact Subsemigroup.subset_closure
  | succ n ih =>
    dsimp [X_seq]
    refine union_subset (union_subset ih ?_) ?_
    · rintro _ ⟨a, ha, b, hb, rfl⟩
      exact Subsemigroup.mul_mem _ (ih ha) (ih hb)
    · simp only [iUnion_subset_iff, SetLike.coe_subset_coe, Subsemigroup.closure_le]
      intro e he x hx
      exact ih hx.1

/-- A semigroup S is locally finite if every finite subset generates a finite subsemigroup. -/
def IsLocallyFinite (S : Type*) [Semigroup S] : Prop :=
  ∀ (X : Set S), X.Finite → (Subsemigroup.closure X : Set S).Finite

/-- Product of a non-empty list of elements in a semigroup `S`. -/
def listProdNE : (u : List S) → u ≠ [] → S
  | [], hu => False.elim (hu rfl)
  | a :: rest, _ => rest.foldl (· * ·) a

lemma foldl_mul_eq_mul_listProdNE (x : S) (v : List S) (hv : v ≠ []) :
    v.foldl (· * ·) x = x * listProdNE v hv := by
  revert x
  induction v with
  | nil => contradiction
  | cons b rest ih =>
    intro x
    cases rest with
    | nil => rfl
    | cons c rest' =>
      have h_rest_ne : c :: rest' ≠ [] := by simp
      change List.foldl (· * ·) (x * b) (c :: rest') = x * List.foldl (· * ·) b (c :: rest')
      rw [ih h_rest_ne (x * b), ih h_rest_ne b, mul_assoc]

lemma listProdNE_concat (u v : List S) (hu : u ≠ []) (hv : v ≠ []) :
    listProdNE (u ++ v) (by simp [hu, hv]) = listProdNE u hu * listProdNE v hv := by
  cases u with
  | nil => contradiction
  | cons a rest =>
    dsimp [listProdNE]
    rw [List.foldl_append]
    exact foldl_mul_eq_mul_listProdNE (rest.foldl (· * ·) a) v hv

/-- Every element in `Subsemigroup.closure X` is generated by
a non-empty list of elements in `X`. -/
lemma mem_closure_iff_exists_list (X : Set S) (s : S) :
    s ∈ Subsemigroup.closure X ↔
    ∃ (u : List S) (hu : u ≠ []), (∀ x ∈ u, x ∈ X) ∧ listProdNE u hu = s := by
  constructor
  · intro hs
    induction hs using Subsemigroup.closure_induction with
    | mem x hx =>
      refine ⟨[x], by simp, by simp [hx], rfl⟩
    | mul x y hx hy ihx ihy =>
      rcases ihx with ⟨ux, hux, hX_x, rfl⟩
      rcases ihy with ⟨uy, huy, hX_y, rfl⟩
      refine ⟨ux ++ uy, by simp [hux, huy], ?_, listProdNE_concat ux uy hux huy⟩
      rintro a ha
      rcases List.mem_append.mp ha with h | h
      · exact hX_x a h
      · exact hX_y a h
  · rintro ⟨u, hu, hX, rfl⟩
    induction u with
    | nil => contradiction
    | cons a rest ih =>
      cases rest with
      | nil => exact Subsemigroup.subset_closure (hX a (by simp))
      | cons b rest' =>
        have h_rest_ne : b :: rest' ≠ [] := by simp
        have ih' := ih h_rest_ne (fun x hx ↦ hX x (List.mem_cons_of_mem a hx))
        have ha : a ∈ Subsemigroup.closure X := Subsemigroup.subset_closure (hX a (by simp))
        have h_eq : listProdNE (a :: b :: rest') hu = a * listProdNE (b :: rest') h_rest_ne := by
          dsimp [listProdNE]
          exact foldl_mul_eq_mul_listProdNE a (b :: rest') h_rest_ne
        rw [h_eq]
        exact Subsemigroup.mul_mem _ ha ih'

lemma listProdNE_eq (u v : List S) (hu : u ≠ []) (hv : v ≠ []) (h : u = v) :
    listProdNE u hu = listProdNE v hv := by
  cases h
  rfl

omit [Semigroup S] in
lemma list_drop_take_append (u : List S) (i j k : ℕ) (hij : i ≤ j) (hjk : j ≤ k) :
    (u.drop i).take (j - i) ++ (u.drop j).take (k - j) = (u.drop i).take (k - i) := by
  have h_drop : u.drop j = (u.drop i).drop (j - i) := by
    rw [List.drop_drop]
    congr 1
    omega
  rw [h_drop]
  have list_take_drop_take (u : List S) (a b : ℕ) :
    u.take a ++ (u.drop a).take b = u.take (a + b) := by grind
  have h_take := list_take_drop_take (u.drop i) (j - i) (k - j)
  have h_eq : j - i + (k - j) = k - i := by omega
  rw [h_eq] at h_take
  exact h_take

omit [Semigroup S] in
lemma list_drop_take_ne_nil (u : List S) (i j : ℕ) (hij : i < j) (hj : j ≤ u.length) :
  (u.drop i).take (j - i) ≠ [] := by
  simp
  grind

lemma listProdNE_split (u : List S) (i j k : ℕ) (hij : i < j) (hjk : j < k) (hk : k ≤ u.length) :
    listProdNE ((u.drop i).take (k - i)) (list_drop_take_ne_nil u i k (hij.trans hjk) hk) =
    listProdNE ((u.drop i).take (j - i)) (list_drop_take_ne_nil u i j hij (hjk.le.trans hk)) *
    listProdNE ((u.drop j).take (k - j)) (list_drop_take_ne_nil u j k hjk hk) := by
  have h_append := list_drop_take_append u i j k hij.le hjk.le
  have h_concat := listProdNE_concat ((u.drop i).take (j - i)) ((u.drop j).take (k - j))
    (list_drop_take_ne_nil u i j hij (hjk.le.trans hk))
    (list_drop_take_ne_nil u j k hjk hk)
  have h_eq := listProdNE_eq ((u.drop i).take (j - i) ++ (u.drop j).take (k - j))
    ((u.drop i).take (k - i))
    (by simp [list_drop_take_ne_nil u i j hij (hjk.le.trans hk),
      list_drop_take_ne_nil u j k hjk hk])
    (list_drop_take_ne_nil u i k (hij.trans hjk) hk) h_append
  rw [h_eq] at h_concat
  exact h_concat

lemma X_seq_inner_lemma (m : ℕ) (ϕ : S →ₙ* T) (X : Set S)
  (u : List S) (eval_T : List S → T)
  (hmul_T : ∀ v w, v ≠ [] → w ≠ [] → eval_T (v ++ w) = eval_T v * eval_T w)
  (h_eval_eq : ∀ w hw, eval_T w = ϕ (listProdNE w hw))
  {n : ℕ} (_ : m < n)
  (s : Split (Fin (u.length + 1)) n)
  (h_ramsey : IsRamsey (wordLabeling eval_T hmul_T u) s)
  (ih : ∀ (i j : Fin (u.length + 1)) (hij : (i : ℕ) < (j : ℕ)),
    (∀ x : Fin (u.length + 1), (i : ℕ) < (x : ℕ) → (x : ℕ) < (j : ℕ) → (s x : ℕ) < m) →
    listProdNE ((u.drop i).take (j - i))
    (list_drop_take_ne_nil u i j hij (by omega)) ∈ X_seq ϕ X (3 * m)) :
  ∀ (i j : Fin (u.length + 1)) (hij : (i : ℕ) < (j : ℕ)),
  (s i : ℕ) = m → (s j : ℕ) = m →
  (∀ x : Fin (u.length + 1), (i : ℕ) < (x : ℕ) → (x : ℕ) < (j : ℕ) → (s x : ℕ) ≤ m) →
  listProdNE ((u.drop i).take (j - i))
    (list_drop_take_ne_nil u i j hij (by omega)) ∈ Subsemigroup.closure
    (X_seq ϕ X (3 * m) ∩ ϕ ⁻¹' {eval_T ((u.drop i).take (j - i))}) := by
  intro i j
  have H : ∀ (len : ℕ) (i j : Fin (u.length + 1))
    (hij : (i : ℕ) < (j : ℕ)) (hlen : (j : ℕ) - (i : ℕ) = len),
    (s i : ℕ) = m → (s j : ℕ) = m →
    (∀ x : Fin (u.length + 1), (i : ℕ) < (x : ℕ) → (x : ℕ) < (j : ℕ) → (s x : ℕ) ≤ m) →
    listProdNE ((u.drop i).take (j - i))
      (list_drop_take_ne_nil u i j hij (by omega)) ∈ Subsemigroup.closure
      (X_seq ϕ X (3 * m) ∩ ϕ ⁻¹' {eval_T ((u.drop i).take (j - i))}) := by
    intro len
    induction len using Nat.strong_induction_on with
    | h len ih_strong =>
      intro i j hij hlen hsi hsj h_between
      by_cases h_cut : ∃ x : Fin (u.length + 1),
        (i : ℕ) < (x : ℕ) ∧ (x : ℕ) < (j : ℕ) ∧ (s x : ℕ) = m
      · let S_cuts :=
          (Finset.univ : Finset (Fin (u.length + 1))).filter
          (fun (x : Fin (u.length + 1)) =>
          (i : ℕ) < (x : ℕ) ∧ (x : ℕ) < (j : ℕ) ∧ (s x : ℕ) = m)
        have h_nonempty : S_cuts.Nonempty := by
          rcases h_cut with ⟨x, hix, hxj, hsx⟩
          exact ⟨x, Finset.mem_filter.mpr ⟨Finset.mem_univ x, ⟨hix, hxj, hsx⟩⟩⟩
        let k := S_cuts.min' h_nonempty
        have hk_mem : k ∈ S_cuts := Finset.min'_mem S_cuts h_nonempty
        have hk_prop := (Finset.mem_filter.mp hk_mem).2
        have hik : (i : ℕ) < (k : ℕ) := hk_prop.1
        have hkj : (k : ℕ) < (j : ℕ) := hk_prop.2.1
        have hsk : (s k : ℕ) = m := hk_prop.2.2
        have h_less : ∀ x : Fin (u.length + 1), (i : ℕ) < (x : ℕ) →
          (x : ℕ) < (k : ℕ) → (s x : ℕ) < m := by
          intro x hix hxk
          have h_bet := h_between x hix (hxk.trans hkj)
          have h_not_eq : ¬ ((s x : ℕ) = m) := by
            intro hc
            have hx_mem : x ∈ S_cuts :=
              Finset.mem_filter.mpr ⟨Finset.mem_univ x, ⟨hix, hxk.trans hkj, hc⟩⟩
            have h_min := Finset.min'_le S_cuts x hx_mem
            omega
          omega
        have h_outer := ih i k hik h_less
        have h_len : (j : ℕ) - (k : ℕ) < len := by omega
        have h_inner :=
          ih_strong ((j : ℕ) - (k : ℕ)) h_len k j hkj rfl hsk hsj
            (fun x hkx hxj => h_between x (hik.trans hkx) hxj)
        have h_split := listProdNE_split u i.1 k.1 j.1 hik hkj (by omega)
        rw [h_split]
        have h_rel_ik : SplitRelation s i k := by
          have h_eq : s i = s k := Fin.ext (by omega)
          refine ⟨h_eq, fun z hz1 hz2 => ?_⟩
          have h_min : min i k = i := min_eq_left (le_of_lt hik)
          rw [h_min]
          change (s z : ℕ) ≤ (s i : ℕ)
          rw [hsi]
          by_cases h_zi : z = i
          · rw [h_zi, hsi]
          · have h_zj : (z : ℕ) < (j : ℕ) := by
              have h_zk : z ≤ k := by
                have h_max : max i k = k := max_eq_right (le_of_lt hik)
                rwa [h_max] at hz2
              omega
            have h_iz : (i : ℕ) < (z : ℕ) := by
              have h_iz' : i ≤ z := by rwa [h_min] at hz1
              omega
            exact h_between z h_iz h_zj
        have h_rel_kj : SplitRelation s k j := by
          have h_eq : s k = s j := Fin.ext (by omega)
          refine ⟨h_eq, fun z hz1 hz2 => ?_⟩
          have h_min : min k j = k := min_eq_left (le_of_lt hkj)
          rw [h_min]
          change (s z : ℕ) ≤ (s k : ℕ)
          rw [hsk]
          by_cases h_zk : z = k
          · rw [h_zk, hsk]
          · by_cases h_zj : z = j
            · rw [h_zj, hsj]
            · have h_kz : (k : ℕ) < (z : ℕ) := by
                have h_kz' : k ≤ z := by rwa [h_min] at hz1
                omega
              have h_zj_lt : (z : ℕ) < (j : ℕ) := by
                have h_max : max k j = j := max_eq_right (le_of_lt hkj)
                have h_zj' : z ≤ j := by rwa [h_max] at hz2
                omega
              exact h_between z (hik.trans h_kz) h_zj_lt
        have h_color_eq :
          (wordLabeling eval_T hmul_T u).σ i k = (wordLabeling eval_T hmul_T u).σ k j :=
          h_ramsey.2 i k k j hik hkj h_rel_ik h_rel_kj h_rel_ik
        have h_color_idem : (wordLabeling eval_T hmul_T u).σ i k *
          (wordLabeling eval_T hmul_T u).σ i k = (wordLabeling eval_T hmul_T u).σ i k :=
          h_ramsey.1 i k j hik hkj h_rel_ik h_rel_kj
        have h_color_total : (wordLabeling eval_T hmul_T u).σ i k *
          (wordLabeling eval_T hmul_T u).σ k j = (wordLabeling eval_T hmul_T u).σ i j :=
          (wordLabeling eval_T hmul_T u).prop i k j hik hkj
        have h_eval_ik_eq_ij : eval_T ((u.drop (i : ℕ)).take ((k : ℕ) - (i : ℕ))) = eval_T
          ((u.drop (i : ℕ)).take ((j : ℕ) - (i : ℕ))) := by
          change (wordLabeling eval_T hmul_T u).σ i k = (wordLabeling eval_T hmul_T u).σ i j
          rw [← h_color_total, ← h_color_eq, h_color_idem]
        have h_eval_kj_eq_ij : eval_T ((u.drop (k : ℕ)).take ((j : ℕ) - (k : ℕ))) = eval_T
          ((u.drop (i : ℕ)).take ((j : ℕ) - (i : ℕ))) := by
          change (wordLabeling eval_T hmul_T u).σ k j = (wordLabeling eval_T hmul_T u).σ i j
          rw [← h_color_eq, ← h_color_total, ← h_color_eq, h_color_idem]
        have h_part1 : listProdNE ((u.drop i).take (k - i))
          (list_drop_take_ne_nil u i k hik (by omega)) ∈ Subsemigroup.closure
          (X_seq ϕ X (3 * m) ∩ ϕ ⁻¹' {eval_T ((u.drop i).take (j - i))}) := by
          apply Subsemigroup.subset_closure
          simp only [mem_inter_iff, mem_preimage, mem_singleton_iff]
          refine ⟨h_outer, ?_⟩
          rw [← h_eval_ik_eq_ij, (h_eval_eq _ _).symm]
        have h_part2 : listProdNE ((u.drop k).take (j - k))
          (list_drop_take_ne_nil u k j hkj (by omega)) ∈ Subsemigroup.closure
          (X_seq ϕ X (3 * m) ∩ ϕ ⁻¹' {eval_T ((u.drop i).take (j - i))}) := by
          have h_eq : eval_T ((u.drop (k : ℕ)).take ((j : ℕ) - (k : ℕ))) = eval_T
            ((u.drop (i : ℕ)).take ((j : ℕ) - (i : ℕ))) := h_eval_kj_eq_ij
          rw [← h_eq]
          exact h_inner
        exact Subsemigroup.mul_mem _ h_part1 h_part2
      · have h_less : ∀ x : Fin (u.length + 1),
          (i : ℕ) < (x : ℕ) → (x : ℕ) < (j : ℕ) → (s x : ℕ) < m := by
          intro x hix hxj
          have h1 := h_between x hix hxj
          have h2 : ¬ ((s x : ℕ) = m) := fun hc ↦ h_cut ⟨x, hix, hxj, hc⟩
          omega
        have h_outer := ih i j hij h_less
        apply Subsemigroup.subset_closure
        simp only [mem_inter_iff, mem_preimage, mem_singleton_iff]
        refine ⟨h_outer, (h_eval_eq _ _).symm⟩
  intro hij hsi hsj h_between
  exact H ((j : ℕ) - (i : ℕ)) i j hij rfl hsi hsj h_between

lemma X_seq_outer_lemma (n : ℕ) (ϕ : S →ₙ* T) (X : Set S)
  (u : List S) (eval_T : List S → T)
  (hmul_T : ∀ v w, v ≠ [] → w ≠ [] → eval_T (v ++ w) = eval_T v * eval_T w)
  (h_eval_eq : ∀ w hw, eval_T w = ϕ (listProdNE w hw))
  (s : Split (Fin (u.length + 1)) n)
  (h_ramsey : IsRamsey (wordLabeling eval_T hmul_T u) s)
  (huX : ∀ (i : ℕ) (hi : i < u.length), u[i] ∈ X) :
  ∀ (m : ℕ) (_ : m ≤ n) (i j : Fin (u.length + 1)) (hij : (i : ℕ) < (j : ℕ)),
  (∀ x : Fin (u.length + 1), (i : ℕ) < (x : ℕ) → (x : ℕ) < (j : ℕ) → (s x : ℕ) < m) →
  listProdNE ((u.drop i).take (j - i))
  (list_drop_take_ne_nil u i j hij (by omega)) ∈ X_seq ϕ X (3 * m) := by
  intro m
  induction m with
  | zero =>
    intro hm i j hij h_less
    have h_empty : ∀ x, (i : ℕ) < x → x < (j : ℕ) → False := by
      intro x hix hxj
      have h1 := h_less ⟨x, by omega⟩ hix hxj
      omega
    have h_j_eq_i_add_one : (j : ℕ) = (i : ℕ) + 1 := by
      by_contra hc
      have h_lt : (i : ℕ) + 1 < (j : ℕ) := by omega
      have h_x_bound : (i : ℕ) + 1 < u.length + 1 := by
        have h_j_bound := j.isLt
        omega
      let x : Fin (u.length + 1) := ⟨(i : ℕ) + 1, h_x_bound⟩
      have h_x_val : (x : ℕ) = (i : ℕ) + 1 := rfl
      have h_false := h_empty x (by omega) (by omega)
      exact h_false
    have h_len : (j : ℕ) - (i : ℕ) = 1 := by omega
    have h_i_lt : (i : ℕ) < u.length := by
      by_contra hc
      have h_j_gt : (j : ℕ) > u.length := by omega
      have h_j_bound := j.isLt
      omega
    have h_drop_take : (u.drop i).take (j - i) = [u[i.1]] := by
      rw [h_len]
      cases u_eq : u.drop (i : ℕ) with
      | nil =>
        have h_len_drop : (u.drop (i : ℕ)).length = 0 := by rw [u_eq, List.length_nil]
        have h_len_drop' : (u.drop (i : ℕ)).length = u.length - (i : ℕ) := by rw [List.length_drop]
        omega
      | cons head tail =>
        have h_head : head = u[i.1] := by
          have h_get : (u.drop i)[0]? = some head := by rw [u_eq, List.getElem?_cons_zero]
          have h_get2 : (u.drop i)[0]? = some u[i.1] := by
            rw [List.getElem?_drop, Nat.add_zero, List.getElem?_eq_getElem h_i_lt]
          simp_all
        rw [h_head]
        rfl
    have h_prod : listProdNE ((u.drop i).take (j - i))
      (list_drop_take_ne_nil u i j hij (by omega)) = u[i.1] := by
      have h_eq_list : (u.drop i).take (j - i) = [u[i.1]] := h_drop_take
      have h_prod_one : listProdNE [u[i.1]] (by simp) = u[i.1] := rfl
      rw [listProdNE_eq _ _ _ _ h_eq_list]
      exact h_prod_one
    rw [h_prod]
    change u[i.1] ∈ X
    exact huX i.1 h_i_lt
  | succ m' ih_m' =>
    intro hm i j hij h_less
    let S_cuts :=
      (Finset.univ : Finset (Fin (u.length + 1))).filter
      (fun (x : Fin (u.length + 1)) =>
      (i : ℕ) < (x : ℕ) ∧ (x : ℕ) < (j : ℕ) ∧ (s x : ℕ) = m')
    have h_mul_mem_gen :
      ∀ n a b, a ∈ X_seq ϕ X n → b ∈ X_seq ϕ X n → a * b ∈ X_seq ϕ X (n + 1) := by
      intro n a b ha hb
      dsimp [X_seq]
      exact Or.inl (Or.inr ⟨a, ha, b, hb, rfl⟩)
    by_cases h_empty : S_cuts = ∅
    · have h_less' : ∀ x :
        Fin (u.length + 1), (i : ℕ) < (x : ℕ) → (x : ℕ) < (j : ℕ) → (s x : ℕ) < m' := by
        intro x hix hxj
        have h_bet := h_less x hix hxj
        by_contra hc
        have h_eq : (s x : ℕ) = m' := by omega
        have h_mem : x ∈ S_cuts :=
          Finset.mem_filter.mpr ⟨Finset.mem_univ x, hix, hxj, h_eq⟩
        rw [h_empty] at h_mem
        revert h_mem
        simp
      have h_ih := ih_m' (by omega) i j hij h_less'
      exact X_seq_mono ϕ X (by omega) h_ih
    · have h_nonempty : S_cuts.Nonempty := Finset.nonempty_of_ne_empty h_empty
      let k_1 := S_cuts.min' h_nonempty
      have hk1_mem := Finset.min'_mem S_cuts h_nonempty
      have hk1_prop := (Finset.mem_filter.mp hk1_mem).2
      let k_r := S_cuts.max' h_nonempty
      have hkr_mem := Finset.max'_mem S_cuts h_nonempty
      have hkr_prop := (Finset.mem_filter.mp hkr_mem).2
      have hik1 : (i : ℕ) < (k_1 : ℕ) := hk1_prop.1
      have h_less_ik1 : ∀ x :
        Fin (u.length + 1), (i : ℕ) < (x : ℕ) → (x : ℕ) < (k_1 : ℕ) → (s x : ℕ) < m' := by
        intro x hix hxk
        have h_bet := h_less x hix (hxk.trans hk1_prop.2.1)
        by_contra hc
        have h_eq : (s x : ℕ) = m' := by omega
        have h_mem : x ∈ S_cuts :=
          Finset.mem_filter.mpr ⟨Finset.mem_univ x, hix, hxk.trans hk1_prop.2.1, h_eq⟩
        have h_le := Finset.min'_le S_cuts x h_mem
        omega
      have h_ih_ik1 := ih_m' (by omega) i k_1 hik1 h_less_ik1
      have hkrj : (k_r : ℕ) < (j : ℕ) := hkr_prop.2.1
      have h_less_krj : ∀ x :
        Fin (u.length + 1), (k_r : ℕ) < (x : ℕ) → (x : ℕ) < (j : ℕ) → (s x : ℕ) < m' := by
        intro x hkx hxj
        have h_min_le : k_1 ≤ k_r := Finset.min'_le S_cuts k_r hkr_mem
        have hikr : (i : ℕ) < (k_r : ℕ) := by omega
        have h_bound := h_less x (by omega) hxj
        by_contra hc
        have h_eq : (s x : ℕ) = m' := by omega
        have h_mem : x ∈ S_cuts :=
          Finset.mem_filter.mpr ⟨Finset.mem_univ x, (by omega), hxj, h_eq⟩
        have h_le := Finset.le_max' S_cuts x h_mem
        omega
      have h_ih_krj := ih_m' (by omega) k_r j hkrj h_less_krj
      by_cases h_eq : k_1 = k_r
      · have hk1j : (k_1 : ℕ) < (j : ℕ) := by rw [h_eq]; exact hkrj
        have h_split := listProdNE_split u i.1 k_1.1 j.1 hik1 hk1j (by omega)
        rw [h_split]
        have h_less_k1j : ∀ x :
          Fin (u.length + 1), (k_1 : ℕ) < (x : ℕ) → (x : ℕ) < (j : ℕ) → (s x : ℕ) < m' := by
          intro x hkx hxj
          have heq2 : (k_1 : ℕ) = (k_r : ℕ) := by rw [h_eq]
          rw [heq2] at hkx
          exact h_less_krj x hkx hxj
        have h_ih_k1j := ih_m' (by omega) k_1 j hk1j h_less_k1j
        have h_prod := h_mul_mem_gen (3 * m') _ _ h_ih_ik1 h_ih_k1j
        exact X_seq_mono ϕ X (by omega) h_prod
      · have hk1kr : (k_1 : ℕ) < (k_r : ℕ) := by
          have hle : k_1 ≤ k_r := Finset.min'_le S_cuts k_r hkr_mem
          omega
        have hk1j : (k_1 : ℕ) < (j : ℕ) := hk1kr.trans hkrj
        have h_split1 := listProdNE_split u i.1 k_1.1 j.1 hik1 hk1j (by omega)
        rw [h_split1]
        have h_split2 := listProdNE_split u k_1.1 k_r.1 j.1 hk1kr hkrj (by omega)
        rw [h_split2]
        by_cases h_no_mid : ∀ x :
          Fin (u.length + 1), (k_1 : ℕ) < (x : ℕ) → (x : ℕ) < (k_r : ℕ) → (s x : ℕ) < m'
        · have h_ih_mid := ih_m' (by omega) k_1 k_r hk1kr h_no_mid
          have h_mul1 := h_mul_mem_gen (3 * m') _ _ h_ih_mid h_ih_krj
          have h_mul2 := h_mul_mem_gen (3 * m' + 1) _ _ (X_seq_mono ϕ X (by omega) h_ih_ik1) h_mul1
          exact X_seq_mono ϕ X (by omega) h_mul2
        · push Not at h_no_mid
          rcases h_no_mid with ⟨k_2, hk12, hk2r, h_not_less⟩
          have hk2_prop : (s k_2 : ℕ) = m' := by
            have h_bet := h_less k_2 (hik1.trans hk12) (hk2r.trans hkrj)
            omega
          have h_rel_12 : SplitRelation s k_1 k_2 := by
            have heq1 : (s k_1 : ℕ) = m' := hk1_prop.2.2
            have heq2 : (s k_2 : ℕ) = m' := hk2_prop
            refine ⟨Fin.ext (by omega), ?_⟩
            intro x hx1 hx2
            have hmin : min k_1 k_2 = k_1 := min_eq_left (le_of_lt hk12)
            have hmax : max k_1 k_2 = k_2 := max_eq_right (le_of_lt hk12)
            rw [hmin] at hx1 ⊢
            rw [hmax] at hx2
            change (s x : ℕ) ≤ (s k_1 : ℕ)
            rw [hk1_prop.2.2]
            have hx1_nat : (k_1 : ℕ) ≤ (x : ℕ) := hx1
            have hx2_nat : (x : ℕ) ≤ (k_2 : ℕ) := hx2
            have h_bound := h_less x (by omega) (by omega)
            omega
          have h_rel_2r : SplitRelation s k_2 k_r := by
            have heq2 : (s k_2 : ℕ) = m' := hk2_prop
            have heqr : (s k_r : ℕ) = m' := hkr_prop.2.2
            refine ⟨Fin.ext (by omega), ?_⟩
            intro x hx1 hx2
            have hmin : min k_2 k_r = k_2 := min_eq_left (le_of_lt hk2r)
            have hmax : max k_2 k_r = k_r := max_eq_right (le_of_lt hk2r)
            rw [hmin] at hx1 ⊢
            rw [hmax] at hx2
            change (s x : ℕ) ≤ (s k_2 : ℕ)
            rw [hk2_prop]
            have hx1_nat : (k_2 : ℕ) ≤ (x : ℕ) := hx1
            have hx2_nat : (x : ℕ) ≤ (k_r : ℕ) := hx2
            have h_bound := h_less x (by omega) (by omega)
            omega
          have h_rel_1r : SplitRelation s k_1 k_r := by
            have heq1 : (s k_1 : ℕ) = m' := hk1_prop.2.2
            have heqr : (s k_r : ℕ) = m' := hkr_prop.2.2
            refine ⟨Fin.ext (by omega), ?_⟩
            intro x hx1 hx2
            have hmin : min k_1 k_r = k_1 := min_eq_left (le_of_lt hk1kr)
            have hmax : max k_1 k_r = k_r := max_eq_right (le_of_lt hk1kr)
            rw [hmin] at hx1 ⊢
            rw [hmax] at hx2
            change (s x : ℕ) ≤ (s k_1 : ℕ)
            rw [hk1_prop.2.2]
            have hx1_nat : (k_1 : ℕ) ≤ (x : ℕ) := hx1
            have hx2_nat : (x : ℕ) ≤ (k_r : ℕ) := hx2
            have h_bound := h_less x (by omega) (by omega)
            omega
          have h_color_eq :
            (wordLabeling eval_T hmul_T u).σ k_1 k_2 = (wordLabeling eval_T hmul_T u).σ k_2 k_r :=
            h_ramsey.2 k_1 k_2 k_2 k_r hk12 hk2r h_rel_12 h_rel_2r h_rel_12
          have h_color_idem : (wordLabeling eval_T hmul_T u).σ k_1 k_2
            * (wordLabeling eval_T hmul_T u).σ k_1 k_2 = (wordLabeling eval_T hmul_T u).σ k_1 k_2 :=
            h_ramsey.1 k_1 k_2 k_r hk12 hk2r h_rel_12 h_rel_2r
          have h_color_total : (wordLabeling eval_T hmul_T u).σ k_1 k_2
            * (wordLabeling eval_T hmul_T u).σ k_2 k_r = (wordLabeling eval_T hmul_T u).σ k_1 k_r :=
            (wordLabeling eval_T hmul_T u).prop k_1 k_2 k_r hk12 hk2r
          have h_color_1r_eq_12 : (wordLabeling eval_T hmul_T u).σ k_1 k_r =
            (wordLabeling eval_T hmul_T u).σ k_1 k_2 := by
            rw [← h_color_total, ← h_color_eq, h_color_idem]
          have h_idem_1r : (wordLabeling eval_T hmul_T u).σ k_1 k_r
            * (wordLabeling eval_T hmul_T u).σ k_1 k_r =
            (wordLabeling eval_T hmul_T u).σ k_1 k_r := by
            rw [h_color_1r_eq_12, h_color_idem]
          let e := eval_T ((u.drop k_1).take (k_r - k_1))
          have he_idem : e * e = e := h_idem_1r
          have h_inner := X_seq_inner_lemma m' ϕ X u eval_T hmul_T h_eval_eq (by omega) s h_ramsey
            (fun i j hij hless => ih_m' (by omega) i j hij hless)
            k_1 k_r hk1kr hk1_prop.2.2 hkr_prop.2.2 (by
              intro x hk1x hxkr
              have hk1x_nat : (k_1 : ℕ) < (x : ℕ) := hk1x
              have hxkr_nat : (x : ℕ) < (k_r : ℕ) := hxkr
              have h_bound := h_less x (by omega) (by omega)
              omega
            )
          have h_subset : (Subsemigroup.closure (X_seq ϕ X (3 * m') ∩ ϕ ⁻¹' {e}) : Set S)
            ⊆ X_seq ϕ X (3 * m' + 1) := by
            intro x hx
            dsimp [X_seq]
            exact Or.inr (Set.mem_iUnion.mpr ⟨e, Set.mem_iUnion.mpr ⟨he_idem, hx⟩⟩)
          have h_k1r_in_3m1 : listProdNE
            ((u.drop k_1).take (k_r - k_1)) _ ∈ X_seq ϕ X (3 * m' + 1) := h_subset h_inner
          have h_k1j_in_3m2 :=
            h_mul_mem_gen (3 * m' + 1) _ _ h_k1r_in_3m1 (X_seq_mono ϕ X (by omega) h_ih_krj)
          have h_total_in_3m3 :=
            h_mul_mem_gen (3 * m' + 2) _ _ (X_seq_mono ϕ X (by omega) h_ih_ik1) h_k1j_in_3m2
          exact X_seq_mono ϕ X (by omega) h_total_in_3m3

/-- **Algebraic Presentation Theorem**:
For a semigroup morphism `ϕ : S →ₙ* T` to a finite semigroup `T` and generator set `X ⊆ S`,
the subsemigroup closure `⟨X⟩_S` coincides with the X_{3|T|} step of the sequence. -/
theorem closure_eq_X_seq [Fintype T] [Nonempty T] (ϕ : S →ₙ* T) (X : Set S) :
    (Subsemigroup.closure X : Set S) = X_seq ϕ X (3 * nS T) := by
  ext s
  constructor
  · intro hs
    rcases (mem_closure_iff_exists_list X s).mp hs with ⟨u, hu, huX, rfl⟩
    let eval_T : List S → T :=
      fun w ↦ if hw : w = [] then Classical.arbitrary T else ϕ (listProdNE w hw)
    have hmul_T : ∀ v w, v ≠ [] → w ≠ [] → eval_T (v ++ w) = eval_T v * eval_T w := by
      intros v w hv hw
      dsimp [eval_T]
      rw [dif_neg (by simp [hv, hw]), dif_neg hv, dif_neg hw]
      rw [listProdNE_concat v w hv hw]
      exact ϕ.map_mul (listProdNE v hv) (listProdNE w hw)
    obtain ⟨split_s, h_norm, h_ramsey⟩ := simon_word eval_T hmul_T u
    have h_eval_eq : ∀ w hw, eval_T w = ϕ (listProdNE w hw) := by
      intros w hw
      dsimp [eval_T]
      rw [dif_neg hw]
    have hX_u : ∀ (i : ℕ) (hi : i < u.length), u[i] ∈ X := by
      intros i hi
      exact huX u[i] (List.get_mem u ⟨i, hi⟩)
    have h_outer := X_seq_outer_lemma (nS T) ϕ X u eval_T hmul_T h_eval_eq split_s h_ramsey hX_u
    have h_le : nS T ≤ nS T := le_refl _
    have hij : (0 : ℕ) < (u.length : ℕ) := by
      have h_len : u.length > 0 := List.length_pos_of_ne_nil hu
      omega
    have h_eval := h_outer (nS T) h_le ⟨0, by omega⟩ ⟨u.length, by omega⟩ hij (by
      intros x hx1 hx2
      exact (split_s x).isLt
    )
    have h_drop_take : (u.drop 0).take (u.length - 0) = u := by
      simp
    have h_eq : listProdNE ((u.drop 0).take (u.length - 0)) (list_drop_take_ne_nil u 0 u.length hij
      (by omega)) = listProdNE u hu := by
      apply listProdNE_eq
      exact h_drop_take
    rw [h_eq] at h_eval
    exact h_eval
  · exact fun hs => X_seq_subset_closure ϕ X (3 * nS T) hs

/-- Condition (1):
For all a ∈ T, {x ∈ X | ϕ(x) = a} ∈ P. -/
def Cond1 (ϕ : S →ₙ* T) (X : Set S) (P : Set (Set S)) : Prop :=
  ∀ a : T, {x ∈ X | ϕ x = a} ∈ P

/-- Condition (1'):
If A ⊆ B and B ∈ P, then A ∈ P (down-closed / hereditary). -/
def Cond1' (P : Set (Set S)) : Prop :=
  ∀ ⦃A B : Set S⦄, A ⊆ B → B ∈ P → A ∈ P

/-- Condition (1''):
X ∈ P. -/
def Cond1'' (X : Set S) (P : Set (Set S)) : Prop :=
  X ∈ P

/-- Condition (2):
For all A, B ∈ P, A ∪ B ∈ P. -/
def Cond2 (P : Set (Set S)) : Prop :=
  ∀ ⦃A B : Set S⦄, A ∈ P → B ∈ P → A ∪ B ∈ P

/-- Condition (3):
For all A, B ∈ P, A * B ∈ P. -/
def Cond3 (P : Set (Set S)) : Prop :=
  ∀ ⦃A B : Set S⦄, A ∈ P → B ∈ P → A * B ∈ P

/-- Condition (4):
For all A ∈ P, if A ⊆ ϕ⁻¹({e}) for an idempotent e ∈ T,
then ⟨A⟩_S ∈ P. -/
def Cond4 (ϕ : S →ₙ* T) (P : Set (Set S)) : Prop :=
  ∀ ⦃A : Set S⦄, A ∈ P → (∃ e : T, e * e = e ∧ A ⊆ ϕ ⁻¹' {e}) →
  (Subsemigroup.closure A : Set S) ∈ P

/-- `Cond1'` (down-closed) and `Cond1''` (X ∈ P) together imply `Cond1`. -/
lemma cond1_of_cond1'_and_cond1'' (ϕ : S →ₙ* T) (X : Set S) (P : Set (Set S))
    (h1' : Cond1' P) (h1'' : Cond1'' X P) : Cond1 ϕ X P := by
  intro a
  have h_sub : {x ∈ X | ϕ x = a} ⊆ X := fun x hx ↦ hx.1
  exact h1' h_sub h1''

omit [Semigroup S] in
/-- Finite union closure under `Cond2`:
If P satisfies `Cond2` and ∅ ∈ P, then any finite union of sets in P is in P. -/
lemma finset_bUnion_mem_P (P : Set (Set S)) (h2 : Cond2 P) (h_empty : ∅ ∈ P)
    {α : Type*} (s : Finset α) (f : α → Set S) (hf : ∀ a ∈ s, f a ∈ P) :
    (⋃ a ∈ s, f a) ∈ P := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    simp [h_empty]
  | insert a s' ha ih =>
    simp only [Finset.mem_insert] at hf
    rw [Finset.set_biUnion_insert]
    exact h2 (hf _ (Or.inl rfl)) (ih (fun b hb ↦ hf b (Or.inr hb)))

/-- **Set-Family Fixed Point Theorem**:
Let S be a semigroup, ϕ : S →ₙ* T a semigroup morphism to a
finite semigroup T, and X ⊆ S. If P ⊆ 𝒫(S)
satisfies conditions (1)-(4) (and down-closedness `Cond1'`),
then ⟨X⟩_S ∈ P. -/
theorem closure_mem_set_family [Finite T] [Nonempty T] (ϕ : S →ₙ* T) (X : Set S) (P : Set (Set S))
    (h1' : Cond1' P)
    (h1 : Cond1 ϕ X P)
    (h2 : Cond2 P)
    (h3 : Cond3 P)
    (h4 : Cond4 ϕ P) :
    (Subsemigroup.closure X : Set S) ∈ P := by
  haveI := Fintype.ofFinite T
  have h_Xn : ∀ n, X_seq ϕ X n ∈ P := by
    intro n
    induction n with
    | zero =>
      dsimp [X_seq]
      have h_eq : X = ⋃ a : T, {x ∈ X | ϕ x = a} := by
        ext x
        simp only [mem_iUnion, mem_sep_iff]
        exact ⟨fun hx ↦ ⟨ϕ x, hx, rfl⟩, fun ⟨a, hx, _⟩ ↦ hx⟩
      rw [h_eq]
      have h_empty : ∅ ∈ P := by
        have a : T := Classical.arbitrary T
        have h_sub : ∅ ⊆ {x ∈ X | ϕ x = a} := empty_subset _
        exact h1' h_sub (h1 a)
      have h_eq' :
        (⋃ a : T, {x ∈ X | ϕ x = a}) = ⋃ a ∈ (Finset.univ : Finset T), {x ∈ X | ϕ x = a} := by
        ext x; simp
      rw [h_eq']
      exact finset_bUnion_mem_P P h2 h_empty Finset.univ _ (fun a _ ↦ h1 a)
    | succ n ih =>
      dsimp [X_seq]
      refine h2 (h2 ih (h3 ih ih)) ?_
      have h_empty : ∅ ∈ P := by
        have : ∅ ⊆ X_seq ϕ X n := empty_subset _
        exact h1' this ih
      have h_eq' : (⋃ (e : T) (_ : e * e = e),
        (Subsemigroup.closure (X_seq ϕ X n ∩ ϕ ⁻¹' {e}) : Set S)) =
        ⋃ e ∈ (Finset.univ : Finset T), ⋃ (_ : e * e = e),
        (Subsemigroup.closure (X_seq ϕ X n ∩ ϕ ⁻¹' {e}) : Set S) := by
        ext x
        simp
      rw [h_eq']
      refine finset_bUnion_mem_P P h2 h_empty Finset.univ _ (fun e _ ↦ ?_)
      by_cases he : e * e = e
      · simp only [he, iUnion_true]
        have h_inter : X_seq ϕ X n ∩ ϕ ⁻¹' {e} ∈ P :=
          h1' inter_subset_left ih
        have h_sub_e : X_seq ϕ X n ∩ ϕ ⁻¹' {e} ⊆ ϕ ⁻¹' {e} := inter_subset_right
        exact h4 h_inter ⟨e, he, h_sub_e⟩
      · simp only [he, iUnion_false]
        exact h_empty
  rw [closure_eq_X_seq ϕ X]
  exact h_Xn (3 * nS T)

/-- The fiber subsemigroup of an idempotent e ∈ T under a morphism `f`. -/
def fiberSubsemigroup (f : S →ₙ* T) (e : T) (he : e * e = e) : Subsemigroup S where
  carrier := f ⁻¹' {e}
  mul_mem' {x y} hx hy := by
    simp only [mem_preimage, mem_singleton_iff] at hx hy ⊢
    rw [f.map_mul, hx, hy, he]

/-- **Brown's Lemma**:
Let `f : S →ₙ* T` be a semigroup morphism. If `T` is locally finite
and for every idempotent `e ∈ T`, the fiber subsemigroup `f ⁻¹' {e}` is locally finite,
then `S` is locally finite. -/
theorem brown_lemma (f : S →ₙ* T)
    (hT : IsLocallyFinite T)
    (h_fibers : ∀ (e : T) (he : e * e = e), IsLocallyFinite (fiberSubsemigroup f e he)) :
    IsLocallyFinite S := by
  intro X hX
  by_cases hX_ne : X.Nonempty
  · obtain ⟨x0, hx0⟩ := hX_ne
    let S' := Subsemigroup.closure X
    let T' := Subsemigroup.closure (f '' X)
    have hT'_fin : (T' : Set T).Finite := hT (f '' X) (hX.image f)
    haveI : Fintype T' := hT'_fin.fintype
    have hT'_nonempty : Nonempty T' :=
      ⟨⟨f x0, Subsemigroup.subset_closure (mem_image_of_mem f hx0)⟩⟩
    haveI : Nonempty (Fin (nS T')) := instNonemptyFin_nS
    let f' : S' →ₙ* T' := {
      toFun := fun ⟨x_val, hx⟩ ↦ ⟨f x_val, by
        induction hx using Subsemigroup.closure_induction with
        | mem a ha => exact Subsemigroup.subset_closure (mem_image_of_mem f ha)
        | mul a b ha hb iha ihb =>
          rw [f.map_mul]
          exact Subsemigroup.mul_mem _ iha ihb⟩
      map_mul' := fun x y ↦ Subtype.ext (f.map_mul x.1 y.1)
    }
    let P : Set (Set S') := { A | A.Finite }
    have h1' : Cond1' P := fun A B hAB hB ↦ hB.subset hAB
    let X_S' : Set S' := range (fun (x : X) ↦ (⟨x.1, Subsemigroup.subset_closure x.2⟩ : S'))
    have h1'' : Cond1'' X_S' P := by
      dsimp [Cond1'', P, X_S']
      haveI : Fintype X := hX.fintype
      exact Set.finite_range _
    have h1 : Cond1 f' X_S' P :=
      cond1_of_cond1'_and_cond1'' f' _ P h1' h1''
    have h2 : Cond2 P := fun A B hA hB ↦ hA.union hB
    have h3 : Cond3 P := fun A B hA hB ↦ Set.Finite.mul hA hB
    have h4 : Cond4 f' P := by
      intro A hA ⟨e', he', hAe'⟩
      have hA_sub_fiber : ∀ x ∈ A, f x.1 = e'.1 := by
        intro x hx
        have : f' x = e' := hAe' hx
        exact Subtype.ext_iff.mp this
      have h_idem : e'.1 * e'.1 = e'.1 := Subtype.ext_iff.mp he'
      have h_lf := h_fibers e'.1 h_idem
      let A_fiber : Set (fiberSubsemigroup f e'.1 h_idem) :=
        { a | ∃ x ∈ A, a.1 = x.1 }
      have hA_fiber_fin : A_fiber.Finite := by
        let g : A_fiber → A := fun ⟨a, ha⟩ ↦
          have hx : ∃ x ∈ A, a.1 = x.1 := ha
          ⟨Classical.choose hx, (Classical.choose_spec hx).1⟩
        have hg_inj : Function.Injective g := by
          intro ⟨a1, ha1⟩ ⟨a2, ha2⟩ hg
          have h_eq : (g ⟨a1, ha1⟩).1.1 = (g ⟨a2, ha2⟩).1.1 := congrArg (fun x ↦ x.1.1) hg
          have h1 : (g ⟨a1, ha1⟩).1.1 = (Classical.choose (ha1 : ∃ x ∈ A, a1.1 = x.1)).1 := rfl
          have h2 : (g ⟨a2, ha2⟩).1.1 = (Classical.choose (ha2 : ∃ x ∈ A, a2.1 = x.1)).1 := rfl
          have h3 : (Classical.choose (ha1 : ∃ x ∈ A, a1.1 = x.1)).1 = a1.1 :=
            (Classical.choose_spec (ha1 : ∃ x ∈ A, a1.1 = x.1)).2.symm
          have h4 : (Classical.choose (ha2 : ∃ x ∈ A, a2.1 = x.1)).1 = a2.1 :=
            (Classical.choose_spec (ha2 : ∃ x ∈ A, a2.1 = x.1)).2.symm
          have h_a1_a2 : a1.1 = a2.1 := by rw [← h3, ← h1, h_eq, h2, h4]
          exact Subtype.ext (Subtype.ext h_a1_a2)
        haveI : Finite A := hA.to_subtype
        haveI : Finite A_fiber := Finite.of_injective g hg_inj
        exact Set.toFinite A_fiber
      have h_closure_fin := h_lf A_fiber hA_fiber_fin
      have hA_sub_fiber_closure : ∀ x ∈ Subsemigroup.closure A, f x.1 = e'.1 := by
        intro x hx
        induction hx using Subsemigroup.closure_induction with
        | mem y hy => exact hA_sub_fiber y hy
        | mul y z hy hz ihy ihz =>
          change f (y.1 * z.1) = e'.1
          rw [f.map_mul, ihy, ihz, h_idem]
      let g : ↥(Subsemigroup.closure A) → ↥(Subsemigroup.closure A_fiber) :=
        fun ⟨x, hx⟩ ↦
          let a_val : fiberSubsemigroup f e'.1 h_idem := ⟨x.1, hA_sub_fiber_closure x hx⟩
          have ha_mem : a_val ∈ Subsemigroup.closure A_fiber := by
            induction hx using Subsemigroup.closure_induction with
            | mem y hy =>
              apply Subsemigroup.subset_closure
              exact ⟨y, hy, rfl⟩
            | mul y z hy hz ihy ihz =>
              exact Subsemigroup.mul_mem _ ihy ihz
          ⟨a_val, ha_mem⟩
      have hg_inj : Function.Injective g := by
        intro ⟨x1, hx1⟩ ⟨x2, hx2⟩ hg
        have h_eq : (g ⟨x1, hx1⟩).1.1 = (g ⟨x2, hx2⟩).1.1 := congrArg (fun x ↦ x.1.1) hg
        exact Subtype.ext (Subtype.ext h_eq)
      haveI : Finite ↥(Subsemigroup.closure A_fiber) := h_closure_fin.to_subtype
      haveI : Finite ↥(Subsemigroup.closure A) := Finite.of_injective g hg_inj
      exact Set.toFinite _
    have h_closure_P := closure_mem_set_family f' _ P h1' h1 h2 h3 h4
    have h_S'_fin : Finite S' := by
      have h_univ : (Subsemigroup.closure X_S' : Set S') = Set.univ := by
        ext ⟨s, hs⟩
        simp only [Set.mem_univ, iff_true]
        induction hs using Subsemigroup.closure_induction with
        | mem x hx =>
          exact Subsemigroup.subset_closure ⟨⟨x, hx⟩, rfl⟩
        | mul x y hx hy ihx ihy =>
          exact Subsemigroup.mul_mem _ ihx ihy
      have h_univ_P : Set.univ ∈ P := h_univ ▸ h_closure_P
      haveI : Finite ↥(Set.univ : Set S') := h_univ_P.to_subtype
      let u_f : S' → ↥(Set.univ : Set S') := fun x ↦ ⟨x, trivial⟩
      have hu_f : Function.Injective u_f := fun x y h ↦ Subtype.ext_iff.mp h
      exact Finite.of_injective u_f hu_f
    exact Set.toFinite _
  · have hX_empty : X = ∅ := not_nonempty_iff_eq_empty.mp hX_ne
    rw [hX_empty]
    simp only [Subsemigroup.closure_empty]
    exact finite_empty

end BrownLemma
