/-
Copyright (c) 2026 Re'em Melamed-Katz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Re'em Melamed-Katz
-/
import Mathlib.Algebra.Group.Pointwise.Set.Basic
import Mathlib.Algebra.Group.Hom.Basic
import Mathlib.Algebra.Group.Subsemigroup.Basic
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Set.Finite.Range
import Mathlib.Data.Fintype.Basic
import Mathlib.Algebra.Group.Pointwise.Set.Finite
import Mathlib.Order.CompleteLattice.Finset
import Project.SimonSplit.Combine
import Project.SimonSplit.Split
import Project.FactorizationTree.FactorizationTree

/-!
# Brown's Lemma and Algebraic Applications

Formalization of Brown's Lemma and the Algebraic Presentation Theorem (Colcombet Theorem 4.1)
using Simon's Factorization Forest Theorem for trees.

## References

* [T. Colcombet, *The Factorization Forest Theorem*][colcombet2008]
-/

namespace BrownLemma

open Set SimonSplit FactorizationTree
open scoped Pointwise

variable {S T : Type*} [Semigroup S] [Semigroup T]

section ClosureSequence

/-- The Simon complexity `nS S` of any non-empty finite semigroup `S` is strictly positive. -/
lemma nS_pos {S : Type*} [Semigroup S] [Fintype S] [Nonempty S] : 0 < nS S := by
  dsimp [nS]
  have h_ne : (Finset.univ.image (fun (x : S) ↦ nSElement x)).Nonempty := by
    obtain ⟨x⟩ : Nonempty S := inferInstance
    exact ⟨_, Finset.mem_image_of_mem _ (Finset.mem_univ x)⟩
  rw [dif_pos h_ne]
  obtain ⟨x⟩ : Nonempty S := inferInstance
  have h_pos : 0 < nSElement x := nSElement_pos x
  have h_mem : nSElement x ∈ Finset.univ.image (fun (x : S) ↦ nSElement x) :=
    Finset.mem_image_of_mem _ (Finset.mem_univ x)
  exact h_pos.trans_le (Finset.le_max' _ _ h_mem)

/-- `Fin (nS S)` is non-empty for any non-empty finite semigroup `S`. -/
instance instNonemptyFin_nS {S : Type*} [Semigroup S] [Fintype S] [Nonempty S] :
    Nonempty (Fin (nS S)) :=
  Fin.pos_iff_nonempty.mp nS_pos

/-- The inductive sequence of subsets `X_seq ϕ X n ⊆ S`:
`X_seq ϕ X 0 = X`.
`X_seq ϕ X (n + 1) = X_seq ϕ X n ∪ (X_seq ϕ X n * X_seq ϕ X n) ∪`
  `⋃_{e ∈ T, e² = e} ⟨X_seq ϕ X n ∩ ϕ⁻¹(e)⟩_S`. -/
def X_seq (ϕ : S →ₙ* T) (X : Set S) : ℕ → Set S
  | 0 => X
  | n + 1 =>
    let Xn := X_seq ϕ X n
    Xn ∪ (Xn * Xn) ∪ ⋃ (e : T) (_ : e * e = e), (Subsemigroup.closure (Xn ∩ ϕ ⁻¹' {e}) : Set S)

/-- Xₙ ⊆ Xₙ₊₁ for all n. -/
lemma X_seq_succ_self (ϕ : S →ₙ* T) (X : Set S) (n : ℕ) :
    X_seq ϕ X n ⊆ X_seq ϕ X (n + 1) := by
  dsimp [X_seq]
  exact subset_union_left.trans subset_union_left

/-- Xₘ ⊆ Xₙ whenever m ≤ n. -/
lemma X_seq_mono (ϕ : S →ₙ* T) (X : Set S) {m n : ℕ} (h : m ≤ n) :
    X_seq ϕ X m ⊆ X_seq ϕ X n := by
  induction h with
  | refl => exact subset_rfl
  | step hk ih => exact ih.trans (X_seq_succ_self ϕ X _)

/-- Xₙ ⊆ ⟨X⟩_S for all n. -/
lemma X_seq_subset_closure (ϕ : S →ₙ* T) (X : Set S) (n : ℕ) :
    X_seq ϕ X n ⊆ Subsemigroup.closure X := by
  induction n with
  | zero => exact Subsemigroup.subset_closure
  | succ n ih =>
    dsimp [X_seq]
    apply union_subset
    · apply union_subset
      · exact ih
      · rintro _ ⟨a, ha, b, hb, rfl⟩
        exact Subsemigroup.mul_mem _ (ih ha) (ih hb)
    · simp only [iUnion_subset_iff, SetLike.coe_subset_coe, Subsemigroup.closure_le]
      intro e he x hx
      exact ih hx.1

/-- A semigroup S is locally finite if every finite subset generates a finite subsemigroup. -/
def IsLocallyFinite (S : Type*) [Semigroup S] : Prop :=
  ∀ (X : Set S), X.Finite → (Subsemigroup.closure X : Set S).Finite

end ClosureSequence

section ListProduct

/-- Product of a non-empty list of elements in a semigroup `S`. -/
def listProdNE : (u : List S) → u ≠ [] → S
  | [], hu => False.elim (hu rfl)
  | a :: rest, _ => rest.foldl (· * ·) a

/-- `List.foldl` multiplication by `x` on the left equals `x * listProdNE v hv`. -/
lemma foldl_mul_eq_mul_listProdNE (x : S) (v : List S) (hv : v ≠ []) :
    v.foldl (· * ·) x = x * listProdNE v hv := by
  revert x
  induction v with
  | nil => contradiction
  | cons b rest ih =>
    intro x
    cases rest with
    | nil => rfl
    | cons c rest' =>
      have h_rest_ne : c :: rest' ≠ [] := by simp
      change List.foldl (· * ·) (x * b) (c :: rest') = x * List.foldl (· * ·) b (c :: rest')
      rw [ih h_rest_ne (x * b), ih h_rest_ne b, mul_assoc]

/-- Product of concatenated non-empty lists is the product of their individual products. -/
lemma listProdNE_concat (u v : List S) (hu : u ≠ []) (hv : v ≠ []) :
    listProdNE (u ++ v) (by simp [hu, hv]) = listProdNE u hu * listProdNE v hv := by
  cases u with
  | nil => contradiction
  | cons a rest =>
    dsimp [listProdNE]
    rw [List.foldl_append]
    exact foldl_mul_eq_mul_listProdNE (rest.foldl (· * ·) a) v hv

/-- Every element in `Subsemigroup.closure X` is generated by
a non-empty list of elements in `X`. -/
lemma mem_closure_iff_exists_list (X : Set S) (s : S) :
    s ∈ Subsemigroup.closure X ↔
    ∃ (u : List S) (hu : u ≠ []), (∀ x ∈ u, x ∈ X) ∧ listProdNE u hu = s := by
  constructor
  · intro hs
    induction hs using Subsemigroup.closure_induction with
    | mem x hx =>
      refine ⟨[x], by simp, by simp [hx], rfl⟩
    | mul x y hx hy ihx ihy =>
      rcases ihx with ⟨ux, hux, hX_x, rfl⟩
      rcases ihy with ⟨uy, huy, hX_y, rfl⟩
      have h_mem : ∀ a ∈ ux ++ uy, a ∈ X := by
        rintro a ha
        rcases List.mem_append.mp ha with h | h
        · exact hX_x a h
        · exact hX_y a h
      exact ⟨ux ++ uy, by simp [hux, huy], h_mem, listProdNE_concat ux uy hux huy⟩
  · rintro ⟨u, hu, hX, rfl⟩
    induction u with
    | nil => contradiction
    | cons a rest ih =>
      cases rest with
      | nil => exact Subsemigroup.subset_closure (hX a (by simp))
      | cons b rest' =>
        have h_rest_ne : b :: rest' ≠ [] := by simp
        have ih' := ih h_rest_ne (fun x hx ↦ hX x (List.mem_cons_of_mem a hx))
        have ha : a ∈ Subsemigroup.closure X := Subsemigroup.subset_closure (hX a (by simp))
        have h_eq : listProdNE (a :: b :: rest') hu = a * listProdNE (b :: rest') h_rest_ne := by
          dsimp [listProdNE]
          exact foldl_mul_eq_mul_listProdNE a (b :: rest') h_rest_ne
        rw [h_eq]
        exact Subsemigroup.mul_mem _ ha ih'

/-- Well-definedness of `listProdNE` with respect to list equality. -/
lemma listProdNE_eq (u v : List S) (hu : u ≠ []) (hv : v ≠ []) (h : u = v) :
    listProdNE u hu = listProdNE v hv := by
  cases h
  rfl

end ListProduct

section TreeLemmas

omit [Semigroup S] in
mutual
  /-- The yield of a Ramsey factorization tree is always non-empty. -/
  lemma tree_value_ne_nil (t : FactorizationTree S) (eval : List S → T)
      (ht : t.IsRamsey eval) : t.value ≠ [] := by
    cases t with
    | leaf a =>
      dsimp [FactorizationTree.value]
      simp
    | binary l r =>
      dsimp [FactorizationTree.value]
      intro h
      rw [List.append_eq_nil_iff] at h
      exact tree_value_ne_nil l eval ht.1 h.1
    | idempotent cs =>
      have hlen := ht.1
      cases cs with
      | nil => contradiction
      | cons c _ =>
        dsimp [FactorizationTree.value, FactorizationTree.listValue]
        intro h
        rw [List.append_eq_nil_iff] at h
        exact tree_value_ne_nil c eval ht.2.1.1 h.1

  /-- The yield of a list of Ramsey factorization trees is non-empty if the list is non-empty. -/
  lemma listTree_value_ne_nil (cs : List (FactorizationTree S)) (eval : List S → T)
      (hcs : FactorizationTree.listIsRamsey eval cs) (hne : cs ≠ []) :
      FactorizationTree.listValue cs ≠ [] := by
    cases cs with
    | nil => contradiction
    | cons c rest =>
      dsimp [FactorizationTree.listValue]
      intro h
      rw [List.append_eq_nil_iff] at h
      exact tree_value_ne_nil c eval hcs.1 h.1
end

mutual
  /-- Product of the yield of a Ramsey tree is contained in `X_seq` at its height. -/
  lemma tree_prod_in_X_seq (ϕ : S →ₙ* T) (X : Set S)
      (eval : List S → T)
      (h_eval : ∀ w hw, eval w = ϕ (listProdNE w hw))
      (t : FactorizationTree S) (ht : t.IsRamsey eval)
      (hX : ∀ x ∈ t.value, x ∈ X)
      (ht_ne : t.value ≠ []) :
      listProdNE t.value ht_ne ∈ X_seq ϕ X t.height := by
    cases t with
    | leaf a =>
      dsimp [FactorizationTree.value] at hX ht_ne ⊢
      dsimp [FactorizationTree.height, X_seq]
      have ha : a ∈ X := hX a (by simp)
      exact ha
    | binary l r =>
      have hl_ramsey := ht.1
      have hr_ramsey := ht.2
      have hl_ne := tree_value_ne_nil l eval hl_ramsey
      have hr_ne := tree_value_ne_nil r eval hr_ramsey
      have hl_X : ∀ x ∈ l.value, x ∈ X := fun x hx ↦
        hX x (by simp [FactorizationTree.value, hx])
      have hr_X : ∀ x ∈ r.value, x ∈ X := fun x hx ↦
        hX x (by simp [FactorizationTree.value, hx])
      have ih_l := tree_prod_in_X_seq ϕ X eval h_eval l hl_ramsey hl_X hl_ne
      have ih_r := tree_prod_in_X_seq ϕ X eval h_eval r hr_ramsey hr_X hr_ne
      have hl_le : l.height ≤ max l.height r.height := le_max_left _ _
      have hr_le : r.height ≤ max l.height r.height := le_max_right _ _
      have ih_l' := X_seq_mono ϕ X hl_le ih_l
      have ih_r' := X_seq_mono ϕ X hr_le ih_r
      have h_val_eq : (FactorizationTree.binary l r).value = l.value ++ r.value := rfl
      have h_prod_eq : listProdNE (FactorizationTree.binary l r).value ht_ne =
          listProdNE l.value hl_ne * listProdNE r.value hr_ne := by
        rw [listProdNE_eq _ _ _ (by simp [hl_ne, hr_ne]) h_val_eq]
        exact listProdNE_concat l.value r.value hl_ne hr_ne
      rw [h_prod_eq]
      have h_in_mul : listProdNE l.value hl_ne * listProdNE r.value hr_ne ∈
          X_seq ϕ X (max l.height r.height) * X_seq ϕ X (max l.height r.height) :=
        ⟨_, ih_l', _, ih_r', rfl⟩
      dsimp [FactorizationTree.height]
      rw [Nat.add_comm 1 (max l.height r.height)]
      dsimp [X_seq]
      exact Or.inl (Or.inr h_in_mul)
    | idempotent cs =>
      obtain ⟨hlen, hcs_ramsey, e, he_idem, he_eval⟩ := ht
      have hcs_ne : cs ≠ [] := by
        rintro rfl
        dsimp at hlen
        omega
      have ih := listTree_prod_in_closure ϕ X eval h_eval cs hcs_ramsey hcs_ne e he_eval hX
      let H := FactorizationTree.listHeight cs
      dsimp [FactorizationTree.height]
      rw [Nat.add_comm 1 H]
      dsimp [X_seq]
      exact Or.inr (Set.mem_iUnion.mpr ⟨e, Set.mem_iUnion.mpr ⟨he_idem, ih⟩⟩)

  /-- Auxiliary induction for the children of an idempotent node. -/
  lemma listTree_prod_in_closure (ϕ : S →ₙ* T) (X : Set S)
      (eval : List S → T)
      (h_eval : ∀ w hw, eval w = ϕ (listProdNE w hw))
      (cs : List (FactorizationTree S)) (hcs : FactorizationTree.listIsRamsey eval cs)
      (hne : cs ≠ []) (e : T)
      (he_eval : ∀ c ∈ cs, eval c.value = e)
      (hX : ∀ x ∈ FactorizationTree.listValue cs, x ∈ X) :
      listProdNE (FactorizationTree.listValue cs) (listTree_value_ne_nil cs eval hcs hne) ∈
        (Subsemigroup.closure (X_seq ϕ X (FactorizationTree.listHeight cs) ∩ ϕ ⁻¹' {e}) :
          Set S) := by
    cases cs with
    | nil => contradiction
    | cons c rest =>
      have hc_ramsey := hcs.1
      have hrest_ramsey := hcs.2
      have hc_ne := tree_value_ne_nil c eval hc_ramsey
      have hc_X : ∀ x ∈ c.value, x ∈ X := fun x hx ↦
        hX x (by simp [FactorizationTree.listValue, hx])
      have ih_c := tree_prod_in_X_seq ϕ X eval h_eval c hc_ramsey hc_X hc_ne
      have hc_eval : eval c.value = e := he_eval c (by simp)
      have hc_phi : ϕ (listProdNE c.value hc_ne) = e := by
        have h1 := h_eval c.value hc_ne
        rw [hc_eval] at h1
        exact h1.symm
      have hc_height_le : c.height ≤ FactorizationTree.listHeight (c :: rest) := by
        dsimp [FactorizationTree.listHeight]
        exact le_max_left _ _
      have ih_c_H := X_seq_mono ϕ X hc_height_le ih_c
      have hc_mem_inter : listProdNE c.value hc_ne ∈
          X_seq ϕ X (FactorizationTree.listHeight (c :: rest)) ∩ ϕ ⁻¹' {e} :=
        ⟨ih_c_H, hc_phi⟩
      have hc_in_closure : listProdNE c.value hc_ne ∈
          Subsemigroup.closure (X_seq ϕ X (FactorizationTree.listHeight (c :: rest)) ∩ ϕ ⁻¹' {e}) :=
        Subsemigroup.subset_closure hc_mem_inter
      by_cases hrest_eq : rest = []
      · subst hrest_eq
        have h_val_eq : FactorizationTree.listValue [c] = c.value := by
          dsimp [FactorizationTree.listValue]
          simp
        have h_prod_eq : listProdNE (FactorizationTree.listValue [c])
            (listTree_value_ne_nil [c] eval hcs (by simp)) = listProdNE c.value hc_ne :=
          listProdNE_eq _ _ _ hc_ne h_val_eq
        rw [h_prod_eq]
        exact hc_in_closure
      · have hrest_ne' : rest ≠ [] := hrest_eq
        have hrest_val_ne := listTree_value_ne_nil rest eval hrest_ramsey hrest_ne'
        have hrest_X : ∀ x ∈ FactorizationTree.listValue rest, x ∈ X :=
          fun x hx ↦ hX x (by simp [FactorizationTree.listValue, hx])
        have he_rest : ∀ t ∈ rest, eval t.value = e :=
          fun t ht ↦ he_eval t (by simp [ht])
        have ih_rest := listTree_prod_in_closure ϕ X eval h_eval rest hrest_ramsey hrest_ne' e
          he_rest hrest_X
        have hrest_height_le : FactorizationTree.listHeight rest ≤
            FactorizationTree.listHeight (c :: rest) := by
          dsimp [FactorizationTree.listHeight]
          exact le_max_right _ _
        have h_subset_inter : (X_seq ϕ X (FactorizationTree.listHeight rest) ∩ ϕ ⁻¹' {e}) ⊆
            (X_seq ϕ X (FactorizationTree.listHeight (c :: rest)) ∩ ϕ ⁻¹' {e}) :=
          Set.inter_subset_inter_left _ (X_seq_mono ϕ X hrest_height_le)
        have h_subset_closure :
            (Subsemigroup.closure (X_seq ϕ X (FactorizationTree.listHeight rest) ∩ ϕ ⁻¹' {e}) :
              Set S) ⊆
            Subsemigroup.closure
              (X_seq ϕ X (FactorizationTree.listHeight (c :: rest)) ∩ ϕ ⁻¹' {e}) := by
          simp only [SetLike.coe_subset_coe, Subsemigroup.closure_le]
          intro x hx
          exact Subsemigroup.subset_closure (h_subset_inter hx)
        have ih_rest_H := h_subset_closure ih_rest
        have h_val_eq : FactorizationTree.listValue (c :: rest) =
            c.value ++ FactorizationTree.listValue rest := rfl
        have h_prod_eq : listProdNE (FactorizationTree.listValue (c :: rest))
            (listTree_value_ne_nil (c :: rest) eval hcs hne) =
            listProdNE c.value hc_ne *
              listProdNE (FactorizationTree.listValue rest) hrest_val_ne := by
          rw [listProdNE_eq _ _ _ (by simp [hc_ne, hrest_val_ne]) h_val_eq]
          exact listProdNE_concat c.value (FactorizationTree.listValue rest) hc_ne hrest_val_ne
        rw [h_prod_eq]
        exact Subsemigroup.mul_mem _ hc_in_closure ih_rest_H
end

end TreeLemmas

section AlgebraicPresentation

/-- Algebraic Presentation Theorem (Colcombet Theorem 4.1): `⟨X⟩_S = X_{3 * nS T}`. -/
theorem closure_eq_X_seq [Fintype T] [Nonempty T] (ϕ : S →ₙ* T) (X : Set S) :
    (Subsemigroup.closure X : Set S) = X_seq ϕ X (3 * nS T) := by
  ext s
  constructor
  · intro hs
    rcases (mem_closure_iff_exists_list X s).mp hs with ⟨u, hu, huX, rfl⟩
    let eval_T : List S → T :=
      fun w ↦ if hw : w = [] then Classical.arbitrary T else ϕ (listProdNE w hw)
    have hmul_T : ∀ v w, v ≠ [] → w ≠ [] → eval_T (v ++ w) = eval_T v * eval_T w := by
      intros v w hv hw
      dsimp [eval_T]
      rw [dif_neg (by simp [hv, hw]), dif_neg hv, dif_neg hw]
      rw [listProdNE_concat v w hv hw]
      exact ϕ.map_mul (listProdNE v hv) (listProdNE w hw)
    obtain ⟨t, ht_val, ht_ramsey, ht_height⟩ :=
      factorization_forest_theorem eval_T hmul_T u hu
    have h_eval_eq : ∀ w hw, eval_T w = ϕ (listProdNE w hw) := by
      intros w hw
      dsimp [eval_T]
      rw [dif_neg hw]
    have ht_X : ∀ x ∈ t.value, x ∈ X := by
      rw [ht_val]
      exact huX
    have ht_ne : t.value ≠ [] := by
      rw [ht_val]
      exact hu
    have h_in_height := tree_prod_in_X_seq ϕ X eval_T h_eval_eq t ht_ramsey ht_X ht_ne
    have h_height_le : t.height ≤ 3 * nS T := by
      omega
    have h_in_3n := X_seq_mono ϕ X h_height_le h_in_height
    have h_val_eq : listProdNE t.value ht_ne = listProdNE u hu := by
      exact listProdNE_eq _ _ _ _ ht_val
    rw [h_val_eq] at h_in_3n
    exact h_in_3n
  · exact fun hs => X_seq_subset_closure ϕ X (3 * nS T) hs

end AlgebraicPresentation

section SetFamilyFixedPoint

/-- Condition (1):
For all a ∈ T, {x ∈ X | ϕ(x) = a} ∈ P. -/
def Cond1 (ϕ : S →ₙ* T) (X : Set S) (P : Set (Set S)) : Prop :=
  ∀ a : T, {x ∈ X | ϕ x = a} ∈ P

/-- Condition (1'):
If A ⊆ B and B ∈ P, then A ∈ P (down-closed / hereditary). -/
def Cond1' (P : Set (Set S)) : Prop :=
  ∀ ⦃A B : Set S⦄, A ⊆ B → B ∈ P → A ∈ P

/-- Condition (1''):
X ∈ P. -/
def Cond1'' (X : Set S) (P : Set (Set S)) : Prop :=
  X ∈ P

/-- Condition (2):
For all A, B ∈ P, A ∪ B ∈ P. -/
def Cond2 (P : Set (Set S)) : Prop :=
  ∀ ⦃A B : Set S⦄, A ∈ P → B ∈ P → A ∪ B ∈ P

/-- Condition (3):
For all A, B ∈ P, A * B ∈ P. -/
def Cond3 (P : Set (Set S)) : Prop :=
  ∀ ⦃A B : Set S⦄, A ∈ P → B ∈ P → A * B ∈ P

/-- Condition (4):
For all A ∈ P, if A ⊆ ϕ⁻¹({e}) for an idempotent e ∈ T,
then ⟨A⟩_S ∈ P. -/
def Cond4 (ϕ : S →ₙ* T) (P : Set (Set S)) : Prop :=
  ∀ ⦃A : Set S⦄, A ∈ P → (∃ e : T, e * e = e ∧ A ⊆ ϕ ⁻¹' {e}) →
  (Subsemigroup.closure A : Set S) ∈ P

/-- `Cond1'` (down-closed) and `Cond1''` (X ∈ P) together imply `Cond1`. -/
lemma cond1_of_cond1'_and_cond1'' (ϕ : S →ₙ* T) (X : Set S) (P : Set (Set S))
    (h1' : Cond1' P) (h1'' : Cond1'' X P) : Cond1 ϕ X P := by
  intro a
  have h_sub : {x ∈ X | ϕ x = a} ⊆ X := fun x hx ↦ hx.1
  exact h1' h_sub h1''

omit [Semigroup S] in
/-- Finite union closure under `Cond2`:
If P satisfies `Cond2` and ∅ ∈ P, then any finite union of sets in P is in P. -/
lemma finset_bUnion_mem_P (P : Set (Set S)) (h2 : Cond2 P) (h_empty : ∅ ∈ P)
    {α : Type*} (s : Finset α) (f : α → Set S) (hf : ∀ a ∈ s, f a ∈ P) :
    (⋃ a ∈ s, f a) ∈ P := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    simp [h_empty]
  | insert a s' ha ih =>
    simp only [Finset.mem_insert] at hf
    rw [Finset.set_biUnion_insert]
    exact h2 (hf _ (Or.inl rfl)) (ih (fun b hb ↦ hf b (Or.inr hb)))

/-- Set-Family Fixed Point Theorem: if `P` satisfies conditions (1)-(4), then `⟨X⟩_S ∈ P`. -/
theorem closure_mem_set_family [Finite T] [Nonempty T] (ϕ : S →ₙ* T) (X : Set S) (P : Set (Set S))
    (h1' : Cond1' P)
    (h1 : Cond1 ϕ X P)
    (h2 : Cond2 P)
    (h3 : Cond3 P)
    (h4 : Cond4 ϕ P) :
    (Subsemigroup.closure X : Set S) ∈ P := by
  haveI := Fintype.ofFinite T
  have h_Xn : ∀ n, X_seq ϕ X n ∈ P := by
    intro n
    induction n with
    | zero =>
      dsimp [X_seq]
      have h_eq : X = ⋃ a : T, {x ∈ X | ϕ x = a} := by
        ext x
        simp only [mem_iUnion, mem_sep_iff]
        exact ⟨fun hx ↦ ⟨ϕ x, hx, rfl⟩, fun ⟨a, hx, _⟩ ↦ hx⟩
      rw [h_eq]
      have h_empty : ∅ ∈ P := by
        have a : T := Classical.arbitrary T
        have h_sub : ∅ ⊆ {x ∈ X | ϕ x = a} := empty_subset _
        exact h1' h_sub (h1 a)
      have h_eq' :
        (⋃ a : T, {x ∈ X | ϕ x = a}) = ⋃ a ∈ (Finset.univ : Finset T), {x ∈ X | ϕ x = a} := by
        ext x; simp
      rw [h_eq']
      exact finset_bUnion_mem_P P h2 h_empty Finset.univ _ (fun a _ ↦ h1 a)
    | succ n ih =>
      dsimp [X_seq]
      have h_empty : ∅ ∈ P := by
        have : ∅ ⊆ X_seq ϕ X n := empty_subset _
        exact h1' this ih
      have h_eq' : (⋃ (e : T) (_ : e * e = e),
        (Subsemigroup.closure (X_seq ϕ X n ∩ ϕ ⁻¹' {e}) : Set S)) =
        ⋃ e ∈ (Finset.univ : Finset T), ⋃ (_ : e * e = e),
        (Subsemigroup.closure (X_seq ϕ X n ∩ ϕ ⁻¹' {e}) : Set S) := by
        ext x
        simp
      have h_union : (⋃ (e : T) (_ : e * e = e),
        (Subsemigroup.closure (X_seq ϕ X n ∩ ϕ ⁻¹' {e}) : Set S)) ∈ P := by
        rw [h_eq']
        apply finset_bUnion_mem_P P h2 h_empty Finset.univ _
        intro e _
        by_cases he : e * e = e
        · simp only [he, iUnion_true]
          have h_inter : X_seq ϕ X n ∩ ϕ ⁻¹' {e} ∈ P :=
            h1' inter_subset_left ih
          have h_sub_e : X_seq ϕ X n ∩ ϕ ⁻¹' {e} ⊆ ϕ ⁻¹' {e} := inter_subset_right
          exact h4 h_inter ⟨e, he, h_sub_e⟩
        · simp only [he, iUnion_false]
          exact h_empty
      exact h2 (h2 ih (h3 ih ih)) h_union
  rw [closure_eq_X_seq ϕ X]
  exact h_Xn (3 * nS T)

end SetFamilyFixedPoint

section BrownLemmaTheorem

/-- The fiber subsemigroup of an idempotent e ∈ T under a morphism `f`. -/
def fiberSubsemigroup (f : S →ₙ* T) (e : T) (he : e * e = e) : Subsemigroup S where
  carrier := f ⁻¹' {e}
  mul_mem' {x y} hx hy := by
    simp only [mem_preimage, mem_singleton_iff] at hx hy ⊢
    rw [f.map_mul, hx, hy, he]

/-- Brown's Lemma: if `T` and all idempotent fiber subsemigroups are locally finite,
then `S` is locally finite. -/
theorem brown_lemma (f : S →ₙ* T)
    (hT : IsLocallyFinite T)
    (h_fibers : ∀ (e : T) (he : e * e = e), IsLocallyFinite (fiberSubsemigroup f e he)) :
    IsLocallyFinite S := by
  intro X hX
  by_cases hX_ne : X.Nonempty
  · obtain ⟨x0, hx0⟩ := hX_ne
    let S' := Subsemigroup.closure X
    let T' := Subsemigroup.closure (f '' X)
    have hT'_fin : (T' : Set T).Finite := hT (f '' X) (hX.image f)
    haveI : Fintype T' := hT'_fin.fintype
    have hT'_nonempty : Nonempty T' :=
      ⟨⟨f x0, Subsemigroup.subset_closure (mem_image_of_mem f hx0)⟩⟩
    haveI : Nonempty (Fin (nS T')) := instNonemptyFin_nS
    let f' : S' →ₙ* T' := {
      toFun := fun ⟨x_val, hx⟩ ↦ ⟨f x_val, by
        induction hx using Subsemigroup.closure_induction with
        | mem a ha => exact Subsemigroup.subset_closure (mem_image_of_mem f ha)
        | mul a b ha hb iha ihb =>
          rw [f.map_mul]
          exact Subsemigroup.mul_mem _ iha ihb⟩
      map_mul' := fun x y ↦ Subtype.ext (f.map_mul x.1 y.1)
    }
    let P : Set (Set S') := { A | A.Finite }
    have h1' : Cond1' P := fun A B hAB hB ↦ hB.subset hAB
    let X_S' : Set S' := range (fun (x : X) ↦ (⟨x.1, Subsemigroup.subset_closure x.2⟩ : S'))
    have h1'' : Cond1'' X_S' P := by
      dsimp [Cond1'', P, X_S']
      haveI : Fintype X := hX.fintype
      exact Set.finite_range _
    have h1 : Cond1 f' X_S' P :=
      cond1_of_cond1'_and_cond1'' f' _ P h1' h1''
    have h2 : Cond2 P := fun A B hA hB ↦ hA.union hB
    have h3 : Cond3 P := fun A B hA hB ↦ Set.Finite.mul hA hB
    have h4 : Cond4 f' P := by
      intro A hA ⟨e', he', hAe'⟩
      have hA_sub_fiber : ∀ x ∈ A, f x.1 = e'.1 := by
        intro x hx
        have : f' x = e' := hAe' hx
        exact Subtype.ext_iff.mp this
      have h_idem : e'.1 * e'.1 = e'.1 := Subtype.ext_iff.mp he'
      have h_lf := h_fibers e'.1 h_idem
      let A_fiber : Set (fiberSubsemigroup f e'.1 h_idem) :=
        { a | ∃ x ∈ A, a.1 = x.1 }
      have hA_fiber_fin : A_fiber.Finite := by
        let g : A_fiber → A := fun ⟨a, ha⟩ ↦
          have hx : ∃ x ∈ A, a.1 = x.1 := ha
          ⟨Classical.choose hx, (Classical.choose_spec hx).1⟩
        have hg_inj : Function.Injective g := by
          intro ⟨a1, ha1⟩ ⟨a2, ha2⟩ hg
          have h_eq : (g ⟨a1, ha1⟩).1.1 = (g ⟨a2, ha2⟩).1.1 := congrArg (fun x ↦ x.1.1) hg
          have h1 : (g ⟨a1, ha1⟩).1.1 = (Classical.choose (ha1 : ∃ x ∈ A, a1.1 = x.1)).1 := rfl
          have h2 : (g ⟨a2, ha2⟩).1.1 = (Classical.choose (ha2 : ∃ x ∈ A, a2.1 = x.1)).1 := rfl
          have h3 : (Classical.choose (ha1 : ∃ x ∈ A, a1.1 = x.1)).1 = a1.1 :=
            (Classical.choose_spec (ha1 : ∃ x ∈ A, a1.1 = x.1)).2.symm
          have h4 : (Classical.choose (ha2 : ∃ x ∈ A, a2.1 = x.1)).1 = a2.1 :=
            (Classical.choose_spec (ha2 : ∃ x ∈ A, a2.1 = x.1)).2.symm
          have h_a1_a2 : a1.1 = a2.1 := by rw [← h3, ← h1, h_eq, h2, h4]
          exact Subtype.ext (Subtype.ext h_a1_a2)
        haveI : Finite A := hA.to_subtype
        haveI : Finite A_fiber := Finite.of_injective g hg_inj
        exact Set.toFinite A_fiber
      have h_closure_fin := h_lf A_fiber hA_fiber_fin
      have hA_sub_fiber_closure : ∀ x ∈ Subsemigroup.closure A, f x.1 = e'.1 := by
        intro x hx
        induction hx using Subsemigroup.closure_induction with
        | mem y hy => exact hA_sub_fiber y hy
        | mul y z hy hz ihy ihz =>
          change f (y.1 * z.1) = e'.1
          rw [f.map_mul, ihy, ihz, h_idem]
      let g : ↥(Subsemigroup.closure A) → ↥(Subsemigroup.closure A_fiber) :=
        fun ⟨x, hx⟩ ↦
          let a_val : fiberSubsemigroup f e'.1 h_idem := ⟨x.1, hA_sub_fiber_closure x hx⟩
          have ha_mem : a_val ∈ Subsemigroup.closure A_fiber := by
            induction hx using Subsemigroup.closure_induction with
            | mem y hy =>
              apply Subsemigroup.subset_closure
              exact ⟨y, hy, rfl⟩
            | mul y z hy hz ihy ihz =>
              exact Subsemigroup.mul_mem _ ihy ihz
          ⟨a_val, ha_mem⟩
      have hg_inj : Function.Injective g := by
        intro ⟨x1, hx1⟩ ⟨x2, hx2⟩ hg
        have h_eq : (g ⟨x1, hx1⟩).1.1 = (g ⟨x2, hx2⟩).1.1 := congrArg (fun x ↦ x.1.1) hg
        exact Subtype.ext (Subtype.ext h_eq)
      haveI : Finite ↥(Subsemigroup.closure A_fiber) := h_closure_fin.to_subtype
      haveI : Finite ↥(Subsemigroup.closure A) := Finite.of_injective g hg_inj
      exact Set.toFinite _
    have h_closure_P := closure_mem_set_family f' _ P h1' h1 h2 h3 h4
    have h_S'_fin : Finite S' := by
      have h_univ : (Subsemigroup.closure X_S' : Set S') = Set.univ := by
        ext ⟨s, hs⟩
        simp only [Set.mem_univ, iff_true]
        induction hs using Subsemigroup.closure_induction with
        | mem x hx =>
          exact Subsemigroup.subset_closure ⟨⟨x, hx⟩, rfl⟩
        | mul x y hx hy ihx ihy =>
          exact Subsemigroup.mul_mem _ ihx ihy
      have h_univ_P : Set.univ ∈ P := h_univ ▸ h_closure_P
      haveI : Finite ↥(Set.univ : Set S') := h_univ_P.to_subtype
      let u_f : S' → ↥(Set.univ : Set S') := fun x ↦ ⟨x, trivial⟩
      have hu_f : Function.Injective u_f := fun x y h ↦ Subtype.ext_iff.mp h
      exact Finite.of_injective u_f hu_f
    exact Set.toFinite _
  · have hX_empty : X = ∅ := not_nonempty_iff_eq_empty.mp hX_ne
    rw [hX_empty]
    simp only [Subsemigroup.closure_empty]
    exact finite_empty

end BrownLemmaTheorem

end BrownLemma
